version: '2.2'

volumes:
  mongo-data:
    external: false

services:
  taaja-mongodb:
    restart: unless-stopped
    image: mongo
    container_name: taaja-mongodb
    expose:
        - 27017
    volumes:
        - mongo-data:/data/db
    healthcheck:
        test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
        interval: 10s
        timeout: 10s
        retries: 5

  taaja-phpmoadmin:
    image: thinkcube/phpmoadmin:latest
    container_name: taaja-phpmoadmin
    restart: "no"
    environment:
        VIRTUAL_HOST: phpmoadmin.taaja.io
        LETSENCRYPT_HOST: phpmoadmin.taaja.io
        LETSENCRYPT_EMAIL: letsencrypt@kara-software.at
    links:
     -  taaja-mongodb:db

  blueracoon:
    image: taaja/blueracoon:latest
    container_name: blueracoon
    restart: unless-stopped
    environment:
        VIRTUAL_HOST: blueracoon.taaja.io
        VIRTUAL_PORT: 8090
        LETSENCRYPT_HOST: blueracoon.taaja.io
        LETSENCRYPT_EMAIL: letsencrypt@kara-software.at
    expose:
      - "8090"
      
  greeneagle:
    image: taaja/greeneagle:latest
    container_name: greeneagle
    restart: unless-stopped
    environment:
        VIRTUAL_HOST: greeneagle.taaja.io
        VIRTUAL_PORT: 8091
        LETSENCRYPT_HOST: greeneagle.taaja.io
        LETSENCRYPT_EMAIL: letsencrypt@kara-software.at
    expose:
      - "8091"

  redcat:
    image: taaja/redcat:latest
    container_name: redcat
    restart: unless-stopped
    environment:
        VIRTUAL_HOST: redcat.taaja.io
        VIRTUAL_PORT: 8092
        LETSENCRYPT_HOST: redcat.taaja.io
        LETSENCRYPT_EMAIL: letsencrypt@kara-software.at
    expose:
      - "8092"
    links:
     -  taaja-mongodb:db

  purpletiger:
    image: taaja/purpletiger:latest
    container_name: purpletiger
    restart: unless-stopped
    environment:
        VIRTUAL_HOST: purpletiger.taaja.io
        VIRTUAL_PORT: 8093
        LETSENCRYPT_HOST: purpletiger.taaja.io
        LETSENCRYPT_EMAIL: letsencrypt@kara-software.at
    expose:
      - "8093"
    links:
     -  taaja-mongodb:db
